# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Technique.find_or_create_by!(name: "Drip Machine", default_ratio: 17.42, default_grind_size: "Medium-Coarse")
Technique.find_or_create_by!(name: "French Press", default_ratio: 12.0, default_grind_size: "Coarse-Medium")
Technique.find_or_create_by!(name: "Chemex", default_ratio: 15.0, default_grind_size: "Medium-Medium")

# Coffee.find_or_create_by!(name: "Generic Light Roast")
# Coffee.find_or_create_by!(name: "Generic Medium Roast")
# Coffee.find_or_create_by!(name: "Generic Dark Roast")
#
# Coffee.find_or_create_by!(name: "Starbucks Bright Sky Blend")
# Coffee.find_or_create_by!(name: "Starbucks Veranda Blend")
# Coffee.find_or_create_by!(name: "Starbucks Breakfast Blend")
# Coffee.find_or_create_by!(name: "Starbucks Pike Place Roast")
# Coffee.find_or_create_by!(name: "Starbucks House Blend")
# Coffee.find_or_create_by!(name: "Starbucks Sumatra")
# Coffee.find_or_create_by!(name: "Starbucks Cafe Verona Blend")
# Coffee.find_or_create_by!(name: "Starbucks French Roast")
# Coffee.find_or_create_by!(name: "Starbucks Morning Joe")
# Coffee.find_or_create_by!(name: "Starbucks Espresso Roast")
# Coffee.find_or_create_by!(name: "Starbucks Italian Roast")
#
# Coffee.find_or_create_by!(name: "Dunkin' Donuts Original Blend")
# Coffee.find_or_create_by!(name: "Dunkin' Donuts Dark")
# Coffee.find_or_create_by!(name: "Dunkin' Donuts Turbo")
# Coffee.find_or_create_by!(name: "Dunkin' Donuts 100% Columbian Coffee")
# Coffee.find_or_create_by!(name: "Dunkin' Donuts French Roast")
# Coffee.find_or_create_by!(name: "Dunkin' Donuts French Vanilla")
# Coffee.find_or_create_by!(name: "Dunkin' Donuts Hazelnut")
# Coffee.find_or_create_by!(name: "Dunkin' Donuts Bakery Series Dulce De Leche Cookie")
# Coffee.find_or_create_by!(name: "Dunkin' Donuts Bakery Series Caramel Coffee Cake")
# Coffee.find_or_create_by!(name: "Dunkin' Donuts Coconut")
# Coffee.find_or_create_by!(name: "Dunkin' Donuts Pumpkin Spice")
# Coffee.find_or_create_by!(name: "Dunkin' Donuts White Chocolate Peppermint")
#
# Coffee.find_or_create_by!(name: "Peet's Coffee Major Dickason's Blend")
# Coffee.find_or_create_by!(name: "Peet's Coffee Arabian Mocha-Java")
# Coffee.find_or_create_by!(name: "Peet's Coffee French Roast")
# Coffee.find_or_create_by!(name: "Peet's Coffee Reserver Kona")
# Coffee.find_or_create_by!(name: "Peet's Coffee Big Bang")
# Coffee.find_or_create_by!(name: "Peet's Coffee Guatemala San Sebastian")
#
# Coffee.find_or_create_by!(name: "Equal Exchange Organic Rebel Rouser")
# Coffee.find_or_create_by!(name: "Equal Exchange Bright Day Brew")
# Coffee.find_or_create_by!(name: "Equal Exchange Organic African Roots")
# Coffee.find_or_create_by!(name: "Equal Exchange Organic Breakfast Blend")
# Coffee.find_or_create_by!(name: "Equal Exchange Organic Love Buzz")
# Coffee.find_or_create_by!(name: "Equal Exchange Organic Mexican")
# Coffee.find_or_create_by!(name: "Equal Exchange Organic French Roast")
# Coffee.find_or_create_by!(name: "Equal Exchange Organic Midnight Sun")
#
# Coffee.find_or_create_by!(name: "Trader Joe's Joe Coffee")
# Coffee.find_or_create_by!(name: "Trader Joe's Dark Coffee")
# Coffee.find_or_create_by!(name: "Trader Joe's Columbian Supreme")
# Coffee.find_or_create_by!(name: "Trader Joe's Organic Fair Trade Breakfast Blend")
# Coffee.find_or_create_by!(name: "Trader Joe's French Roast")
